db:
  image: mysql:8
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: pf3db
    MYSQL_USER: pf3user
    MYSQL_PASSWORD: pf3password
  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql